services:

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: "synapse"
      POSTGRES_PASSWORD: "${DATABASE_PASS:?must provide a database password}"
      POSTGRES_DB: "synapse"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./database/docker-healthcheck
        target: /usr/local/bin/docker-healthcheck
        read_only: true
      - type: bind
        source: "${DATABASE_DATA_PATH:?must provide a path to store database data on the host}"
        target: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "docker-healthcheck"]
      interval: 30s
      timeout: 30s
      start_period: 60s
      start_interval: 5s
      retries: 3
    restart: unless-stopped

  synapse:
    image: matrixdotorg/synapse:latest
    environment:
      SYNAPSE_CONFIG_DIR: /data/synapse
      SYNAPSE_CONFIG_PATH: /data/synapse/homeserver.yaml
      SYNAPSE_WORKER: "synapse.app.homeserver"
    volumes:
      - type: bind
        source: "${SYNAPSE_DATA_PATH:?must provide a path to store Synapse data on the host}"
        target: /data
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      start_period: 30s
      start_interval: 5s
      retries: 3
    restart: unless-stopped

  element:
    image: vectorim/element-web:latest
    volumes:
      - type: bind
        source: "${ELEMENT_DATA_PATH:?must provide a path to store Element data on the host}/element/config.json"
        target: /app/config.json
        read_only: true
      - type: bind
        source: "${ELEMENT_DATA_PATH}/element/config.json"
        target: "/app/config.chat.${SYNAPSE_SERVER_NAME}.json"
        read_only: true
    depends_on:
      - synapse
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/version"]
      interval: 15s
      timeout: 5s
      start_period: 30s
      start_interval: 5s
      retries: 3
    restart: unless-stopped

  caddy:
    image: caddy:2.7-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - type: bind
        source: ./caddy/docker-healthcheck
        target: /usr/local/bin/docker-healthcheck
        read_only: true
      - type: bind
        source: "${CADDY_DATA_PATH:?must provide a path to store Caddy data on the host}"
        target: /data
      - type: bind
        source: "${CADDY_DATA_PATH}/caddy/Caddyfile"
        target: /etc/caddy/Caddyfile
        read_only: true
    depends_on:
      - element
    healthcheck:
      test: ["CMD", "docker-healthcheck"]
      interval: 15s
      timeout: 5s
      start_period: 120s
      start_interval: 5s
      retries: 3
    restart: unless-stopped
