#!/bin/sh
set -eo pipefail

synapse_response="$(curl -fSs http://localhost:8888/health)"
element_response="$(curl -fSs http://localhost:8888/version)"

if [[ $synapse_response == "OK" && $element_response == "1."* ]]; then
  exit 0
fi

exit 1
